const styles = (theme) => ({
  root: {
    background: [theme.primary],
    height: "100vh",
    "& .MuiDivider-root": {
      borderTop: "1px solid #252525",
      margin: "70px auto 55px",
      maxWidth: "40%",
    },
  },
  ColorBlock: {
    backgroundColor: "#ffb400",
    height: "200%",
    left: "-83%",
    // position: "fixed",
    top: "-50%",
    WebkitTransform: "rotate(-15deg)",
    transform: "rotate(-15deg)",
    width: "100%",
    display: "block!important",
  },
  mainBox: {
    color: "#fffff",
    // display: "flex",
    alignItems: "center",
    height: "100vh",
    // margin: "50px",
    "& h2": {
      color: "#fff",
      margin: "0 0",
    },
  },
  firstBox: {
    backgroundPosition: "top",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    borderRadius: "30px",
    boxShadow: "0 0 7px rgba(0,0,0,.9)",
    height: "calc(100vh - 80px)",
    left: "40px",
    top: "40px",
    zIndex: "1",
    width: "33.33333333%",
    position: "absolute",
    margin: "50px 0 0 0 !important",
  },
  secondGrid: {
    "&.MuiGrid-root": {
      margin: "7% 0 0 33.33% !important",
      // marginLeft: "33.33333333%",
    },
  },
  secondBox: {
    color: "#fff",
    maxWidth: "600px",
    margin: "0 auto",
    "& h1": {
      fontSize: "51px",
      lineHeight: "62px",
      fontWeight: "700",
      margin: "18px 0 10px",
      position: "relative",
      color: "#ffb400",
      paddingLeft: "70px",
      "&::before": {
        backgroundColor: "#ffb400",
        content: '""',
        position: "absolute",
        left: "0",
        top: "29px",
        height: "4px",
        width: "40px",
        borderRadius: "10px",
      },
    },
    "& span": {
      color: "#fff",
    },
    "& p": {
      margin: "15px 0 28px",
      fontSize: "16px",
      lineHeight: "35px",
      fontFamily: '"Open Sans",sans-serif',
    },
    "& img": {
      display: "none",
    },
  },
  Btn: {
    "&.MuiButton-root": {
      backgroundColor: "transparent",
      borderRadius: "35px",
      color: "#fff",
      cursor: "pointer",
      //  cursor: "pointer!important",
      display: "inline-block",
      fontSize: "15px",
      fontWeight: "600",
      lineHeight: "1.4",
      outline: "none!important",
      overflow: "hidden",
      padding: "16px 70px 16px 35px",
      position: "relative",
      textAlign: "center",
      textDecoration: "none!important",
      textOverflow: "ellipsis",
      textTransform: "uppercase",
      transition: "all .25s ease-in-out",
      WebkitUserSelect: "none",
      userSelect: "none",
      verticalAlign: "middle",
      whiteSpace: "nowrap",
      zIndex: "1",
      border: "1px solid #ffb400",
      "&::before": {
        backgroundColor: "#ffb400",
        bottom: "0",
        content: '""',
        left: "0",
        position: "absolute",
        right: "0",
        top: "0",
        // WebkitTransform: "translateX(100%)",
        transform: "translateX(100%)",
        transition: "all .3s ease-out",
        zIndex: "-1",
      },
      "&:hover::before": {
        transform: "translateX(0)",
        // "&::before": {
        // backgroundColor: "#ffb400",
        // },
      },
    },
  },

  BtnSpan: {
    position: "relative",
    zIndex: "2",
    color: "#fff",
    transition: "all .3s ease-out",
  },
  BtnIcon: {
    position: "absolute",
    right: "-1px",
    top: "-1px",
    bottom: "0",
    width: "55px",
    height: "55px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: "19px",
    color: "#fff",
    borderRadius: "50%",
    backgroundColor: "#ffb400",
    "&::before": {
      content: '"\f061"',
      boxSizing: "border-box",
    },
  },

  //  About Page
  TitleSection: {
    margin: "0 auto",
    width: "100%",
    position: "relative",
    padding: "80px 0",
    textAlign: "center",
    fontFamily: "Poppins,sans-serif",
    "& h1": {
      color: "#fff",
      margin: "0",
      fontSize: "56px",
      fontWeight: "900!important",
      textTransform: "uppercase",
    },
  },
  TitleSectionspan: {
    color: "hsla(0,0%,100%,.07)",
    fontFamily: "Poppins,sans-serif",
    fontSize: "110px",
    fontWeight: "800",
    left: "0",
    letterSpacing: "10px",
    lineHeight: ".7",
    position: "absolute",
    right: "0",
    textTransform: "uppercase",
    top: "50%",
    WebkitTransform: "translateY(-50%)",
    transform: "translateY(-50%)",
  },
  FirstBoxStack: {
    // "& .MuiStack-root": {
    padding: "0 15px",
    // },
    "& h3": {
      fontSize: "26px",
      paddingBottom: "22px",
      fontWeight: "600",
      margin: "0 0",
      color: "#fff",
      textTransform: "uppercase",
      fontFamily: "Poppins,sans-serif",
    },
  },
  PresonalInfoUl: {
    display: "flex",
    flexWrap: "wrap",
    fontFamily: "Open Sans,sans-serif",
    color: "#fff",
    listStyle: "none",
    paddingLeft: "0",
    marginBottom: "1rem",
    marginTop: "0",
    "& li": {
      flex: "0 0 50%",
      maxWidth: "50%",
      paddingBottom: "20px",
    },
    "& .MuiLinearProgress-root": {
      height: "10px",
      background: "#fff",
      width: "85%",
      borderRadius: "5px",
    },
    "& .MuiLinearProgress-bar": {
      backgroundColor: "#ffcd00",
    },
  },

  // Chart Css
  chartsGrid: {
    display: "flex",
  },

  //
  infoTitle: {
    opacity: ".8",
    textTransform: "capitalize",
  },
  spanTitle: {
    display: "flex",
    alignItems: "center",
    // justifyContent: "space-between",
    padding: "0 5px",
    "& p ": {
      opacity: ".8",
      textTransform: "capitalize",
      margin: "0 5px 0 0",
    },
  },
  spandiv: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-around",
  },

  spanTitleAns: {
    fontWeight: "600",
  },
  aboutBoxes: {
    border: "1px solid #252525",
    borderRadius: "5px",
    padding: "20px 30px 25px 40px",
    marginBottom: "30px",
    "& h3": {
      display: "inline-block",
      fontSize: "50px",
      fontWeight: "700",
      margin: "0",
      color: "#ffb400",
      position: "relative",
      fontFamily: "Poppins,sans-serif",
      "&::after": {
        content: '"+"',
        fontSize: "33px",
        fontWeight: "300",
        position: "absolute",
        right: "-24px",
        top: "2px",
      },
    },
    "& p": {
      paddingLeft: "45px",
      fontFamily: "Open Sans,sans-serif",
      textTransform: "uppercase",
      position: "relative",
      color: "#fff",
      margin: "0 0",
      "&::before": {
        background: "#777",
        content: '""',
        height: "1px",
        left: "0",
        position: "absolute",
        top: "13px",
        width: "30px",
      },
      "& span": {
        display: "block",
      },
    },
  },
  Titles: {
    "& h3": {
      fontSize: "26px",
      textAlign: "center",
      textTransform: "uppercase",
      fontWeight: "600",
      padding: "0 0 3rem 0",
      margin: "0 0",
      fontFamily: "'Poppins'",
    },
  },
  circularBox: {
    "&.MuiBox-root": {
      display: "flex",
      flexDirection: "column",
      position: "absolute",
      "& .MuiCircularProgress-root": {
        width: "auto !important",
        height: "auto !important",
      },
      "& .MuiCircularProgress-svg": {
        height: "100px",
        width: "100px",
        color: "yellow",
      },
      "& .MuiTypography-root": {
        position: "relative",
        fontSize: "30px",
        fontWeight: "600",
        // transform: "translate(24px, -26px)",
        color: "#fff",
      },
    },
  },

  //  Experience
  resume_box: {
    "&.MuiBox-root": {
      "& ul": {
        listStyle: "none",
        margin: "0",
        padding: "0",
      },
      "& li": {
        margin: "0 0 50px",
        padding: "0 20px 0 60px",
        position: "relative",
        "&::after": {
          borderLeft: "1px solid #333",
          bottom: "0",
          content: '""',
          left: "20px",
          position: "absolute",
          top: "0",
        },
      },
      "& h5": {
        fontSize: "18px",
        margin: "7px 0 10px",
        fontFamily: "Poppins,sans-serif",
        textTransform: "uppercase",
      },
      "& p": {
        color: "#eee",
        fontSize: "14px",
        margin: "0",
        fontFamily: "Open Sans,sans-serif",
      },
    },
  },
  Icon: {
    backgroundColor: "#ffb400",
    borderRadius: "50%",
    color: "#fff",
    height: "40px",
    left: "0",
    lineHeight: "40px",
    position: "absolute",
    right: "0",
    textAlign: "center",
    width: "40px",
    zIndex: "1",
    "& svg": {
      verticalAlign: "text-bottom",
    },
  },
  time: {
    backgroundColor: "#252525",
    borderRadius: "20px",
    color: "#fff",
    display: "inline-block",
    fontSize: "12px",
    fontWeight: "600",
    marginBottom: "12px",
    opacity: ".8",
    padding: "1px 10px",
    textTransform: "uppercase",
  },
  place: {
    fontSize: "15px",
    fontWeight: "600",
    opacity: ".8",
    paddingLeft: "26px",
    position: "relative",
    fontFamily: "Open Sans,sans-serif",
    "&::before": {
      backgroundColor: "#fff",
      content: '""',
      height: "2px",
      left: "7px",
      opacity: ".8",
      position: "absolute",
      top: "9px",
      width: "10px",
    },
  },
  // Contact page
  custom_title: {
    fontSize: "26px",
    fontWeight: "600",
    textTransform: "uppercase",
    paddingBottom: "1rem",
    marginBottom: "0",
    fontFamily: "Poppins,sans-serif",
    cursor: "none",
  },
  contact_p: {
    fontFamily: "Open Sans,sans-serif",
    marginBottom: "1.5rem",
    marginTop: "0",
  },
  Custom_span_contact: {
    fontWeight: "600",
    lineHeight: "25px",
    marginBottom: "20px",
    paddingLeft: "50px",
    paddingTop: "5px",
    fontFamily: "Open Sans,sans-serif",
    position: "relative",
    marginTop: "0",
    "& span ": {
      fontWeight: "400",
      opacity: ".8",
      paddingBottom: "0",
      textTransform: "uppercase",
      display: "block",
    },
    "& a": {
      color: "#fff",
      cursor: "pointer",
      textDecoration: "none",
    },
    "& svg": {
      fontSize: "33px",
      left: "0",
      top: "10px",
      color: "#ffb400",
      position: "absolute",
    },
  },
  social: {
    marginLeft: "-5px",
    paddingTop: "15px",
    marginBottom: "3rem",
    listStyle: "none",
    paddingLeft: "0",
    "& li": {
      display: "inline-block",
    },
    "& a": {
      background: "#2b2a2a",
      borderRadius: "50%",
      color: "#fff",
      // display: "inline-block",
      fontSize: "17px",
      height: "40px",
      lineHeight: "42px",
      margin: "0 6px",
      textAlign: "center",
      transition: ".3s",
      width: "40px",
      textDecoration: "underline",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      "&:hover": {
        backgroundColor: "#ffb400",
      },
    },
  },
  contactform: {
    paddingLeft: 30,
    "& .MuiTextField-root": {
      width: "100%",
    },
    "& .MuiOutlinedInput-root": {
      margin: "0 15px 30px",
      borderRadius: "30px",
      border: "1px solid #111",
      outline: "none!important",

      "&.Mui-focused": {
        border: "1px solid #111",
        "& .MuiOutlinedInput-notchedOutline": {
          border: "1px solid #ffcd00",
          borderRadius: "30px",
        },
      },
    },

    "& input": {
      background: "#252525",
      border: "1px solid #111",
      borderRadius: "30px",
      color: "#fff",
      outline: "none!important",
      padding: "15px 25px",
      transition: ".3s",
      width: "100%",
    },
    "& textarea": {
      background: "#252525",
      border: "1px solid #111",
      borderRadius: "30px",
      color: "#fff",
      height: "200px",
      outline: "none!important",
      overflow: "hidden",
      padding: "12px 26px",
      transition: ".3s",
      width: "88%",
      resize: "none",
      fontFamily: "inherit",
      fontSize: "inherit",
      lineHeight: "inherit",
      margin: "0 0px 0px 15px",
      "&:focus": {
        border: "1px solid #ffcd00",
      },
    },
  },

  //  Media query
  "@media (max-width: 1200px)": {
    secondBox: {
      maxWidth: "450px",
      "& h1": {
        fontSize: "42px",
        lineHeight: "52px",
        paddingLeft: 0,
        "&::before": {
          content: "none",
        },
      },
    },
  },
  "@media (max-width: 991px)": {
    firstBox: {
      display: "none",
    },
    secondGrid: {
      margin: "0 auto !important",
      textAlign: "center",
    },
    secondBox: {
      "& p": {
        fontSize: "15px",
      },
      "& img": {
        display: "block",
        border: "4px solid #252525",
        borderRadius: "50%",
        height: "270px",
        margin: "0 auto 25px",
        width: "270px",
        verticalAlign: "middle",
      },
    },
  },
  "@media (max-width:768px)": {
    chartsGrid: {
      display: "flex !important",
      flexDirection: "column !important",
      "& h6": {
        textAlign: "center",
        width: "100%",
      },
    },
  },
});

export default styles;
